/* * Copyright (c) 2019 Negocio Varejo. All rights reserved. * */
package br.com.negocio.varejo.tag.emitter.views;

import br.com.negocio.varejo.tag.emitter.views.custom.NVDesktopPane;
import br.com.negocio.varejo.tag.emitter.utilities.DateUtil;
import br.com.negocio.varejo.tag.emitter.utilities.ViewUtil;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author derickfelix
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        customSettings();
    }
    
    private void customSettings()
    {
        ViewUtil.addIcon(this);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        lblInfoDate.setText(DateUtil.format(new Date()));
        lblUsername.setText(System.getProperty("user.name").toUpperCase());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new NVDesktopPane();
        paneCompanyName = new javax.swing.JPanel();
        lblCompanyName = new javax.swing.JLabel();
        paneUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        paneVersion = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();
        paneInfoDate = new javax.swing.JPanel();
        lblInfoDate = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuQuery = new javax.swing.JMenu();
        mniProduct = new javax.swing.JMenuItem();
        menuTagEmission = new javax.swing.JMenu();
        mniTagEmission = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emissao de Etiquetas");

        desktop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        paneCompanyName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblCompanyName.setFont(lblCompanyName.getFont().deriveFont(lblCompanyName.getFont().getSize()-3f));
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setText("NEGOCIO VAREJO");

        javax.swing.GroupLayout paneCompanyNameLayout = new javax.swing.GroupLayout(paneCompanyName);
        paneCompanyName.setLayout(paneCompanyNameLayout);
        paneCompanyNameLayout.setHorizontalGroup(
            paneCompanyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCompanyNameLayout.setVerticalGroup(
            paneCompanyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyNameLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblCompanyName)
                .addGap(5, 5, 5))
        );

        paneUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblUsername.setFont(lblUsername.getFont().deriveFont(lblUsername.getFont().getSize()-3f));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USUARIO");

        javax.swing.GroupLayout paneUsernameLayout = new javax.swing.GroupLayout(paneUsername);
        paneUsername.setLayout(paneUsernameLayout);
        paneUsernameLayout.setHorizontalGroup(
            paneUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneUsernameLayout.setVerticalGroup(
            paneUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUsernameLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneVersion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblVersion.setFont(lblVersion.getFont().deriveFont(lblVersion.getFont().getSize()-3f));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("VERSÃO 1.1.0");

        javax.swing.GroupLayout paneVersionLayout = new javax.swing.GroupLayout(paneVersion);
        paneVersion.setLayout(paneVersionLayout);
        paneVersionLayout.setHorizontalGroup(
            paneVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneVersionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneVersionLayout.setVerticalGroup(
            paneVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneVersionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblVersion)
                .addGap(5, 5, 5))
        );

        paneInfoDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblInfoDate.setFont(lblInfoDate.getFont().deriveFont(lblInfoDate.getFont().getSize()-3f));
        lblInfoDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoDate.setText("01/06/2019");

        javax.swing.GroupLayout paneInfoDateLayout = new javax.swing.GroupLayout(paneInfoDate);
        paneInfoDate.setLayout(paneInfoDateLayout);
        paneInfoDateLayout.setHorizontalGroup(
            paneInfoDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInfoDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoDate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneInfoDateLayout.setVerticalGroup(
            paneInfoDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInfoDateLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblInfoDate)
                .addGap(5, 5, 5))
        );

        menuQuery.setText("Consulta");

        mniProduct.setText("Produtos");
        mniProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProductActionPerformed(evt);
            }
        });
        menuQuery.add(mniProduct);

        menuBar.add(menuQuery);

        menuTagEmission.setText("Emissao");

        mniTagEmission.setText("Etiqueta");
        mniTagEmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTagEmissionActionPerformed(evt);
            }
        });
        menuTagEmission.add(mniTagEmission);

        menuBar.add(menuTagEmission);

        menuHelp.setText("Ajuda");

        mniAbout.setText("Sobre");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        menuHelp.add(mniAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desktop)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneInfoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneInfoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniTagEmissionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniTagEmissionActionPerformed
    {//GEN-HEADEREND:event_mniTagEmissionActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        TagEmitterForm tagEmitter = new TagEmitterForm(this);
        desktop.add(tagEmitter);
        tagEmitter.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_mniTagEmissionActionPerformed

    private void mniProductActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniProductActionPerformed
    {//GEN-HEADEREND:event_mniProductActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        ProductQueryForm pqf = new ProductQueryForm(this);
        desktop.add(pqf);
        pqf.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_mniProductActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniAboutActionPerformed
    {//GEN-HEADEREND:event_mniAboutActionPerformed
        JOptionPane.showMessageDialog(this, "Negocio Varejo - Emissor Etiqueta\nVersão 1.0.0", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniAboutActionPerformed

    public javax.swing.JDesktopPane getDesktop()
    {
        return desktop;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblInfoDate;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuQuery;
    private javax.swing.JMenu menuTagEmission;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniProduct;
    private javax.swing.JMenuItem mniTagEmission;
    private javax.swing.JPanel paneCompanyName;
    private javax.swing.JPanel paneInfoDate;
    private javax.swing.JPanel paneUsername;
    private javax.swing.JPanel paneVersion;
    // End of variables declaration//GEN-END:variables
}
