/* * Copyright (c) 2020 Negocio Varejo. All rights reserved. * */
package br.com.negociovarejo.extensionplus.views;

import br.com.negociovarejo.extensionplus.models.Customer;
import br.com.negociovarejo.extensionplus.repositories.CustomerRepository;
import br.com.negociovarejo.extensionplus.utilities.MessageUtil;
import br.com.negociovarejo.extensionplus.utilities.ViewUtil;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author derickfelix
 */
public class MainForm extends javax.swing.JFrame {

    private final CustomerRepository repository;
    private Customer customer;
   
    /**
     * Creates new form MainForm
     */
    public MainForm()
    {
        this.repository = new CustomerRepository();
        customSettings();
        initComponents();
    }
    
    private void customSettings()
    {
        ViewUtil.addIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelForm = new javax.swing.JPanel();
        lblTaxPayerRegistration = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtTaxPayerRegistration = new javax.swing.JFormattedTextField();
        lblCode = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VR Software + Extension");
        setResizable(false);

        panelForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTaxPayerRegistration.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblTaxPayerRegistration.setText("CPF/CNPJ");

        txtCode.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCode.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtCodeKeyPressed(evt);
            }
        });

        txtCustomer.setEditable(false);
        txtCustomer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        try
        {
            txtTaxPayerRegistration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        txtTaxPayerRegistration.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTaxPayerRegistration.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtTaxPayerRegistrationKeyPressed(evt);
            }
        });

        lblCode.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblCode.setText("Código");

        lblCustomer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblCustomer.setText("Cliente");

        btnExit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-button-icon.png"))); // NOI18N
        btnExit.setText("Sair");
        btnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExitActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon.png"))); // NOI18N
        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addGap(0, 228, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCustomer)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaxPayerRegistration)
                            .addComponent(lblTaxPayerRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxPayerRegistration)
                    .addComponent(lblCode))
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTaxPayerRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(495, 271));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCodeKeyPressed
    {//GEN-HEADEREND:event_txtCodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setCursor(ViewUtil.WAIT_CURSOR);
            try {
                Long code = Long.parseLong(txtCode.getText());
                customer = repository.find(code);

                if (customer != null) {
                    txtCustomer.setText(customer.getName());
                    txtTaxPayerRegistration.setText(customer.getTaxPayerRegistration());
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente não encontrado!", "VR Software + Extension", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException e) {
                MessageUtil.showException(this, "Campo Inválido!", e);
            }
            setCursor(ViewUtil.DEFAULT_CURSOR);
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        saveChanges();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTaxPayerRegistrationKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtTaxPayerRegistrationKeyPressed
    {//GEN-HEADEREND:event_txtTaxPayerRegistrationKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            saveChanges();
        }
    }//GEN-LAST:event_txtTaxPayerRegistrationKeyPressed

    private void saveChanges()
    {
        setCursor(ViewUtil.WAIT_CURSOR);
        if (customer != null) {
            customer.setTaxPayerRegistration(txtTaxPayerRegistration.getText());

            if (customer.getTaxPayerRegistration().length() != 18) {
                JOptionPane.showMessageDialog(this, "CNPJ Inválido!", "VR Software + Extension", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try {
                repository.save(customer);
                JOptionPane.showMessageDialog(this, "Informações salvas com sucesso!", "VR Software + Extension", JOptionPane.INFORMATION_MESSAGE);
            } catch (RuntimeException e) {
                MessageUtil.showException(this, e);
            }
            txtCode.setText("");
            txtTaxPayerRegistration.setText("");
            txtCustomer.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente primeiro!", "VR Software + Extension", JOptionPane.WARNING_MESSAGE);
        }
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblTaxPayerRegistration;
    private javax.swing.JPanel panelForm;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JFormattedTextField txtTaxPayerRegistration;
    // End of variables declaration//GEN-END:variables
}
