/* * Copyright (c) 2018 VR Fortaleza. All rights reserved. * */
package br.com.vrfortaleza.upextension.views;

import br.com.vrfortaleza.upextension.wholesale.forms.ProductQueryForm;
import br.com.vrfortaleza.upextension.utilities.DateUtil;
import br.com.vrfortaleza.upextension.utilities.NumberUtil;
import br.com.vrfortaleza.upextension.utilities.ViewUtil;
import br.com.vrfortaleza.upextension.wholesale.forms.LaunchSaleForm;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Date: Feb 28, 2018.
 *
 * @author Derick Felix
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form VendaForm
     */
    public MainForm()
    {
        initComponents();
        customSettings();
    }

    private void customSettings()
    {
        ViewUtil.addIcon(this);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        lblInfoDate.setText(DateUtil.format(new Date(), "dd/MM/yyyy"));
        lblUsername.setText(System.getProperty("user.name").toUpperCase());
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblStore = new javax.swing.JLabel();
        spnStore = new javax.swing.JSpinner();
        paneUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        paneStoreNumber = new javax.swing.JPanel();
        lblStoreNumber = new javax.swing.JLabel();
        paneAppVersion = new javax.swing.JPanel();
        lblAppVersion = new javax.swing.JLabel();
        paneCompany = new javax.swing.JPanel();
        lblCompany = new javax.swing.JLabel();
        desktop = new br.com.vrfortaleza.upextension.views.custom.BackgroundDesktopPane();
        paneInfoDate = new javax.swing.JPanel();
        lblInfoDate = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuQuery = new javax.swing.JMenu();
        miCategory = new javax.swing.JMenuItem();
        miPeriod = new javax.swing.JMenuItem();
        menuWholesale = new javax.swing.JMenu();
        mniQueryWholesalePrice = new javax.swing.JMenuItem();
        miLaunchSale = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        mniCheckForUpdates = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VR Software Fortaleza - Up Extension");
        setLocationByPlatform(true);

        lblStore.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        lblStore.setText("Loja: ");

        spnStore.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        spnStore.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnStore.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                spnStoreStateChanged(evt);
            }
        });

        paneUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblUsername.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USUARIO");

        javax.swing.GroupLayout paneUsernameLayout = new javax.swing.GroupLayout(paneUsername);
        paneUsername.setLayout(paneUsernameLayout);
        paneUsernameLayout.setHorizontalGroup(
            paneUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneUsernameLayout.setVerticalGroup(
            paneUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUsernameLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblUsername)
                .addGap(4, 4, 4))
        );

        paneStoreNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblStoreNumber.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        lblStoreNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStoreNumber.setText("LOJA 01");

        javax.swing.GroupLayout paneStoreNumberLayout = new javax.swing.GroupLayout(paneStoreNumber);
        paneStoreNumber.setLayout(paneStoreNumberLayout);
        paneStoreNumberLayout.setHorizontalGroup(
            paneStoreNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStoreNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStoreNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneStoreNumberLayout.setVerticalGroup(
            paneStoreNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStoreNumberLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblStoreNumber)
                .addGap(4, 4, 4))
        );

        paneAppVersion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblAppVersion.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        lblAppVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppVersion.setText("VERSÃO 1.2.1");

        javax.swing.GroupLayout paneAppVersionLayout = new javax.swing.GroupLayout(paneAppVersion);
        paneAppVersion.setLayout(paneAppVersionLayout);
        paneAppVersionLayout.setHorizontalGroup(
            paneAppVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAppVersionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAppVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneAppVersionLayout.setVerticalGroup(
            paneAppVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAppVersionLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblAppVersion)
                .addGap(4, 4, 4))
        );

        paneCompany.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblCompany.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("VR SOFTWARE FORTALEZA");

        javax.swing.GroupLayout paneCompanyLayout = new javax.swing.GroupLayout(paneCompany);
        paneCompany.setLayout(paneCompanyLayout);
        paneCompanyLayout.setHorizontalGroup(
            paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCompanyLayout.setVerticalGroup(
            paneCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompanyLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblCompany)
                .addGap(4, 4, 4))
        );

        desktop.setBackground(new java.awt.Color(205, 205, 205));
        desktop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        paneInfoDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));

        lblInfoDate.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        lblInfoDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoDate.setText("01/01/2001");

        javax.swing.GroupLayout paneInfoDateLayout = new javax.swing.GroupLayout(paneInfoDate);
        paneInfoDate.setLayout(paneInfoDateLayout);
        paneInfoDateLayout.setHorizontalGroup(
            paneInfoDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInfoDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoDate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneInfoDateLayout.setVerticalGroup(
            paneInfoDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInfoDateLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblInfoDate)
                .addGap(4, 4, 4))
        );

        menuQuery.setText("Consultas");

        miCategory.setText("Gerenciamento Categoria");
        miCategory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miCategoryActionPerformed(evt);
            }
        });
        menuQuery.add(miCategory);

        miPeriod.setText("Venda Período");
        miPeriod.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miPeriodActionPerformed(evt);
            }
        });
        menuQuery.add(miPeriod);

        menuBar.add(menuQuery);

        menuWholesale.setText("Atacado");

        mniQueryWholesalePrice.setText("Consulta Preço Venda");
        mniQueryWholesalePrice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniQueryWholesalePriceActionPerformed(evt);
            }
        });
        menuWholesale.add(mniQueryWholesalePrice);

        miLaunchSale.setText("Lançamento Venda");
        miLaunchSale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miLaunchSaleActionPerformed(evt);
            }
        });
        menuWholesale.add(miLaunchSale);

        menuBar.add(menuWholesale);

        menuHelp.setText("Ajuda");

        mniCheckForUpdates.setText("Procurar por Atualizações");
        mniCheckForUpdates.setEnabled(false);
        menuHelp.add(mniCheckForUpdates);

        mniAbout.setText("Sobre");
        mniAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniAboutActionPerformed(evt);
            }
        });
        menuHelp.add(mniAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnStore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneStoreNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneInfoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desktop))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnStore, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneInfoDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneAppVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneStoreNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(paneCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spnStoreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnStoreStateChanged
        lblStoreNumber.setText("LOJA " + NumberUtil.fixedDigits(2, spnStore.getValue().toString()));
    }//GEN-LAST:event_spnStoreStateChanged

    private void miPeriodActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miPeriodActionPerformed
    {//GEN-HEADEREND:event_miPeriodActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        SalesPeriodForm period = new SalesPeriodForm(this);
        desktop.add(period);
        period.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_miPeriodActionPerformed

    private void miCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miCategoryActionPerformed
    {//GEN-HEADEREND:event_miCategoryActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        CategoryForm category = new CategoryForm(this);
        desktop.add(category);
        category.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_miCategoryActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniAboutActionPerformed
    {//GEN-HEADEREND:event_mniAboutActionPerformed
        JOptionPane.showMessageDialog(this, "VR Software Fortaleza - Up Extension\nVersão 1.2.1", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniQueryWholesalePriceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniQueryWholesalePriceActionPerformed
    {//GEN-HEADEREND:event_mniQueryWholesalePriceActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        ProductQueryForm productQueryForm = new ProductQueryForm();
        desktop.add(productQueryForm);
        productQueryForm.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_mniQueryWholesalePriceActionPerformed

    private void miLaunchSaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miLaunchSaleActionPerformed
    {//GEN-HEADEREND:event_miLaunchSaleActionPerformed
        setCursor(ViewUtil.WAIT_CURSOR);
        LaunchSaleForm launchSaleForm = new LaunchSaleForm(this);
        //LaunchSaleProductForm launchSaleForm = new LaunchSaleProductForm();
        //ProductQueryForm launchSaleForm = new ProductQueryForm(true);
        desktop.add(launchSaleForm);
        launchSaleForm.setVisible(true);
        setCursor(ViewUtil.DEFAULT_CURSOR);
    }//GEN-LAST:event_miLaunchSaleActionPerformed

    
    public String getUsername()
    {
        return lblUsername.getText();
    }
    
    public String getStoreNumber()    
    {
        return lblStoreNumber.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel lblAppVersion;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblInfoDate;
    private javax.swing.JLabel lblStore;
    private javax.swing.JLabel lblStoreNumber;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuQuery;
    private javax.swing.JMenu menuWholesale;
    private javax.swing.JMenuItem miCategory;
    private javax.swing.JMenuItem miLaunchSale;
    private javax.swing.JMenuItem miPeriod;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniCheckForUpdates;
    private javax.swing.JMenuItem mniQueryWholesalePrice;
    private javax.swing.JPanel paneAppVersion;
    private javax.swing.JPanel paneCompany;
    private javax.swing.JPanel paneInfoDate;
    private javax.swing.JPanel paneStoreNumber;
    private javax.swing.JPanel paneUsername;
    private javax.swing.JSpinner spnStore;
    // End of variables declaration//GEN-END:variables

}
