/* * Copyright (c) 2018 VR Fortaleza. All rights reserved. * */
package br.com.vrfortaleza.upextension.repositories.impl;

import br.com.vrfortaleza.upextension.repositories.FileRepository;
import br.com.vrfortaleza.upextension.utilities.FileUtil;
import java.util.ArrayList;
import java.util.List;

/**
 * Reads the file generated by the {@code VRMaster.jar}.
 *
 * Date: Mar 2, 2018.
 *
 * @author Derick Felix
 */
public class FileSalePeriodRepository implements FileRepository<String[]> {

    @Override
    public List<String[]> read(String path)
    {
        List<String> file = FileUtil.read(path);
        List<String[]> rows = new ArrayList<>();
        file.remove(0);
        /* remove line of headers */
        String delim = getSeparator(file);

        for (String line : file) {
            String[] tokens = line.split(delim);
            String[] row = new String[tokens.length + 3];
            System.arraycopy(tokens, 0, row, 0, tokens.length);
            rows.add(row);
        }

        return rows;
    }

    /**
     * Determine the delimiter type of a file, returns 'unknown' if that file
     * hasn't a supported delimeter.
     *
     * @return a delimiter as a string
     */
    private String getSeparator(List<String> file)
    {
        String line = file.get(0);
        
        if (line.contains("  ") || line.contains(" ,")) {
            /* for these delimeters the "data" and "quantidade" column are not
             * separated correctly, so we need to add one space to support them.
             */
            for (int i = 0; i < file.size(); i++) {
                String l = file.get(i);
                String a = l.substring(0, 16);
                String b = l.substring(16, l.length() - 1);
                file.set(i, a + " " + b);
            }
        }

        return FileUtil.SEPARATOR(line);
    }
}
